### ISSUE TITLE
Getting 'TypeError: Cannot read property 'Inbox.sol' of undefined' when running compile.js on Inbox.sol

### ISSUE THREAD

**Issue by razsa** [owanhunte/ethereum-solidity-course-updated-code#4]
{
  "name": "inbox",
  "version": "1.0.0",
  "description": "",
  "main": "compile.js",
  "scripts": {
    "test": ""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "solc": "^0.5.15"
  }
}

Any ideas?

**Comment by owanhunte** [comment]
hi @razsa can you please show your `Inbox.sol` smart contract and your accompanying `compile.js` Node script?

**Comment by razsa** [comment]
Inbox.sol
```
pragma solidity >=0.5.0 <0.7.0;

contract Inbox {
	string public message;

constructor(string memory initialMessage) public {
	message = initialMessage;
	}

function setMessage(string memory newMessage) public {
	message = newMessage;
	}
}
```
compile.js
```
const path = require('path');
const fs = require('fs');
const solc = require('solc');

const inboxPath = path.resolve(__dirname, 'contracts', 'Inbox.sol');
const source = fs.readFileSync(inboxPath, 'utf8');

const input = {
	langauge: 'Solidity',
	sources: {
		'Inbox.sol' :{
			content: source
		}
	},
	settings: {
		outputSelection: {
			'*':{
				'*': ['*']
			}
		}
	}
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
module.exports = output.contracts['Inbox.sol'].Inbox;

```

**Comment by owanhunte** [comment]
ok so I see no difference between what you have above for your smart contract and node script compared to what's [here](https://github.com/owanhunte/ethereum-solidity-course-updated-code/blob/master/inbox/contracts/Inbox.sol) and [here](https://github.com/owanhunte/ethereum-solidity-course-updated-code/blob/master/inbox/compile.js) respectively. Assuming that you specified a `0.5.x` version of solc in your package.json (I specified `^0.5.15` in mine as shown [here](https://github.com/owanhunte/ethereum-solidity-course-updated-code/blob/master/inbox/package.json#L16)) then your smart contract should compile without error. Can you confirm the solc version requirement you have specified in your package.json?

**Comment by owanhunte** [comment]
Hi @razsa since you opened this issue, the Inbox smart contract has been updated to Solidity 0.8 and the [compile](https://github.com/owanhunte/ethereum-solidity-course-updated-code/blob/main/inbox/compile.js) and [deploy](https://github.com/owanhunte/ethereum-solidity-course-updated-code/blob/main/inbox/deploy.js) scripts brought up-to-date with the latest versions of the Node.js libraries they are using. If possible, can you please test things with the code from the current state of this repo and let me know if you get any errors when running `compile.js` for the `Inbox` smart contract?

**Comment by owanhunte** [comment]
Since this issue has had no comments from it's author in well over 2 years now, I'll go ahead and close it due to inactivity.
