### ISSUE TITLE
All course projects in Typescript

### ISSUE THREAD

**Issue by Muzzamil1** [owanhunte/ethereum-solidity-course-updated-code#41]
Hi @owanhunte,

First of all thanks for all your hard work on keeping the course projects up to date.
I'm planning to build all the projects with Typescript. May I use your code as the base?

**Comment by owanhunte** [comment]
@Muzzamil1 of course you may use my code as the base! That's why I created this repo, to benefit the community in any way possible. I look forward to seeing what you produce!

**Comment by Muzzamil1** [comment]
Thanks, @owanhunte.
I will share the links here as well.

**Comment by Muzzamil1** [comment]
Hi @owanhunte,

Here is the Inbox project in the typescript version.
https://github.com/Muzzamil1/ethereum-solidity-course-updated-code-typescript/tree/main/1.Inbox

I have added the `eslint` with many plugins for linting and formatting Typescript code. `solhint` and `ethlint/solium` linters for the Solidity code.
If you know any plugin which can improve productivity and instills best practices, please do let me know we will add that. 

If you got time please have a look at the project. Your feedback will be appreciated. 
Regards,

**Comment by owanhunte** [comment]
@Muzzamil1 sorry for the late reply, glad to hear you have made progress with your TS version of this repo. Things are a bit busy for me right now but I'll see if I can take a look at your repo in detail sometime early next week. I did take a peek though and I'm liking what you have done so far. Once I take a detail look I'll give more meaningful feedback.

**Comment by Muzzamil1** [comment]
Thanks!
Will be looking forward to it.

**Comment by owanhunte** [comment]
Hi @Muzzamil1, hope you're doing well. It's been quite a while since my last reply on this issue so my apologies for that. I'm just about wrapping up (within about 1 week's time) full updates to all the code provided in this repo as part of my efforts to keep all my versions of the udemy.com course code examples up-to-date. After that I will actually take another look at your TS repo and give my feedback there if that's ok with you. For now, I'll go ahead and close this issue here.
