### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by SuriaAniza** [owanhunte/ethereum-solidity-course-updated-code#42]
Hi Mr Owan, i would like to say the gratitude to you for the update of the course. I would like to ask question on why there are error on retrieving the wallet address in the page index.js 

    render() {
       
       return <div> {this.props.campaigns[0]}
            
            </div>

    } 

Thanks in advance.

**Comment by owanhunte** [comment]
@SuriaAniza - I'm happy to know that you find this repo useful. I haven't been able to keep it as up-to-date as I would like, however, as I've been getting busier with my blockchain work over the past months. Can you provide more detailed information as to what you are referring to exactly? Which file is generating the error? Can you link directly to the file here in the comments please?

**Comment by owanhunte** [comment]
Hi @SuriaAniza this issue is rather old now and no longer valid since there have been significant upgrades to the Next.js framework and the various packages the Kickstart app needs to use, over the past year. I'm in the process of updating this repo's version of the Kickstart app to the latest Next.js and third-party library versions. Once I've completed that update, please be sure to fork, clone and attempt a deployment of the app at that point of the repo state and see if you still get any errors on retrieving the wallet address, and if so, open a new issue then.

For now, this issue will be closed.
